import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    const { workspace_id } = await req.json();
    if (!workspace_id) throw new Error("Missing workspace_id");

    const oneWeekAgo = new Date();
    oneWeekAgo.setDate(oneWeekAgo.getDate() - 7);

    // Gather weekly data
    const [channelStatsRes, videosPublishedRes, dealsClosedRes, goalRes, profileRes] =
      await Promise.all([
        supabase
          .from("youtube_channel_stats")
          .select("subscriber_count, fetched_at")
          .eq("workspace_id", workspace_id)
          .order("fetched_at", { ascending: false })
          .limit(2),
        supabase
          .from("video_queue")
          .select("title")
          .eq("workspace_id", workspace_id)
          .eq("status", "published")
          .gte("updated_at", oneWeekAgo.toISOString()),
        supabase
          .from("deals")
          .select("title, value")
          .eq("workspace_id", workspace_id)
          .eq("stage", "closed_won")
          .gte("closed_at", oneWeekAgo.toISOString()),
        supabase
          .from("growth_goals")
          .select("target_value, current_value, target_date")
          .eq("workspace_id", workspace_id)
          .eq("status", "active")
          .limit(1)
          .maybeSingle(),
        supabase
          .from("profiles")
          .select("email")
          .eq("id", (await supabase.from("workspace_members").select("user_id").eq("workspace_id", workspace_id).eq("role", "owner").single()).data?.user_id)
          .single(),
      ]);

    const snapshots = channelStatsRes.data ?? [];
    const currentSubs = snapshots[0]?.subscriber_count ?? 0;
    const previousSubs = snapshots[1]?.subscriber_count ?? currentSubs;
    const subGrowth = currentSubs - previousSubs;
    const videosPublished = videosPublishedRes.data?.length ?? 0;
    const dealsClosed = dealsClosedRes.data ?? [];
    const revenueThisWeek = dealsClosed.reduce((s, d) => s + (d.value ?? 0), 0);
    const goal = goalRes.data;

    const goalProgress = goal
      ? ((goal.current_value / goal.target_value) * 100).toFixed(1)
      : "N/A";

    // Build HTML report
    const html = `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
      <h1 style="font-size: 24px; margin-bottom: 4px;">Weekly Growth Report</h1>
      <p style="color: #666; font-size: 14px;">Hustling Labs · ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}</p>

      <div style="background: #f9fafb; border-radius: 12px; padding: 20px; margin: 20px 0;">
        <h2 style="font-size: 16px; margin-bottom: 16px;">Subscriber Growth</h2>
        <p style="font-size: 32px; font-weight: bold; margin: 0;">${currentSubs.toLocaleString()}</p>
        <p style="color: ${subGrowth >= 0 ? "#10b981" : "#ef4444"}; font-size: 14px;">
          ${subGrowth >= 0 ? "+" : ""}${subGrowth.toLocaleString()} this week
        </p>
        ${goal ? `<p style="color: #666; font-size: 12px;">${goalProgress}% toward ${goal.target_value.toLocaleString()} goal</p>` : ""}
      </div>

      <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin: 20px 0;">
        <div style="background: #f9fafb; border-radius: 12px; padding: 16px;">
          <p style="color: #666; font-size: 12px; text-transform: uppercase; margin: 0 0 4px;">Videos Published</p>
          <p style="font-size: 24px; font-weight: bold; margin: 0;">${videosPublished}</p>
        </div>
        <div style="background: #f9fafb; border-radius: 12px; padding: 16px;">
          <p style="color: #666; font-size: 12px; text-transform: uppercase; margin: 0 0 4px;">Revenue</p>
          <p style="font-size: 24px; font-weight: bold; margin: 0;">$${revenueThisWeek.toLocaleString()}</p>
        </div>
      </div>

      ${dealsClosed.length > 0 ? `
      <h3 style="font-size: 14px;">Deals Closed This Week</h3>
      <ul style="padding-left: 20px;">
        ${dealsClosed.map((d) => `<li>${d.title} — $${(d.value ?? 0).toLocaleString()}</li>`).join("")}
      </ul>
      ` : ""}

      <p style="color: #999; font-size: 11px; margin-top: 30px; border-top: 1px solid #eee; padding-top: 12px;">
        Generated by Mission Control Hub
      </p>
    </div>`;

    // Try to send via Resend if configured
    const { data: resendIntegration } = await supabase
      .from("workspace_integrations")
      .select("config")
      .eq("workspace_id", workspace_id)
      .eq("integration_key", "resend")
      .eq("enabled", true)
      .maybeSingle();

    let emailSent = false;
    const recipientEmail = profileRes.data?.email;

    if (resendIntegration?.config?.api_key && recipientEmail) {
      const resendRes = await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${resendIntegration.config.api_key}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          from: resendIntegration.config.from_email || "noreply@example.com",
          to: [recipientEmail],
          subject: `Weekly Report: ${subGrowth >= 0 ? "+" : ""}${subGrowth} subs · $${revenueThisWeek.toLocaleString()} revenue`,
          html,
        }),
      });
      emailSent = resendRes.ok;
    }

    return new Response(
      JSON.stringify({
        success: true,
        email_sent: emailSent,
        report: {
          subscriber_count: currentSubs,
          subscriber_growth: subGrowth,
          videos_published: videosPublished,
          deals_closed: dealsClosed.length,
          revenue: revenueThisWeek,
          goal_progress: goalProgress,
        },
      }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error: unknown) {
    return new Response(
      JSON.stringify({ success: false, error: error instanceof Error ? error.message : String(error) }),
      {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  }
});
