
-- Viral playbook runs
CREATE TABLE public.viral_playbook_runs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  youtube_video_id text NOT NULL,
  video_title text NOT NULL DEFAULT '',
  viral_score int NOT NULL DEFAULT 0,
  trigger_reason text NOT NULL DEFAULT 'threshold',
  status text NOT NULL DEFAULT 'active',
  started_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  -- Performance tracking
  views_at_trigger int NOT NULL DEFAULT 0,
  views_current int NOT NULL DEFAULT 0,
  subs_at_trigger int NOT NULL DEFAULT 0,
  subs_gained int NOT NULL DEFAULT 0,
  leads_generated int NOT NULL DEFAULT 0,
  deals_generated int NOT NULL DEFAULT 0,
  revenue_attributed numeric NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.viral_playbook_runs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "workspace members can manage viral_playbook_runs"
  ON public.viral_playbook_runs FOR ALL TO authenticated
  USING (public.is_workspace_member(workspace_id))
  WITH CHECK (public.is_workspace_member(workspace_id));
CREATE INDEX idx_viral_playbook_runs_ws ON public.viral_playbook_runs(workspace_id, status);

-- Checklist items for each playbook run
CREATE TABLE public.viral_playbook_checklist (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  run_id uuid NOT NULL REFERENCES public.viral_playbook_runs(id) ON DELETE CASCADE,
  workspace_id uuid NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  step_order int NOT NULL DEFAULT 0,
  title text NOT NULL,
  description text,
  category text NOT NULL DEFAULT 'general',
  is_completed boolean NOT NULL DEFAULT false,
  completed_at timestamptz,
  completed_by uuid,
  auto_generated boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.viral_playbook_checklist ENABLE ROW LEVEL SECURITY;
CREATE POLICY "workspace members can manage viral_playbook_checklist"
  ON public.viral_playbook_checklist FOR ALL TO authenticated
  USING (public.is_workspace_member(workspace_id))
  WITH CHECK (public.is_workspace_member(workspace_id));

-- Queued conversion assets generated by AI
CREATE TABLE public.viral_conversion_assets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  run_id uuid NOT NULL REFERENCES public.viral_playbook_runs(id) ON DELETE CASCADE,
  workspace_id uuid NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  asset_type text NOT NULL,
  title text NOT NULL,
  content text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'draft',
  published_at timestamptz,
  metadata jsonb DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.viral_conversion_assets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "workspace members can manage viral_conversion_assets"
  ON public.viral_conversion_assets FOR ALL TO authenticated
  USING (public.is_workspace_member(workspace_id))
  WITH CHECK (public.is_workspace_member(workspace_id));
